/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_contral_enable
* Dimensions:  176 * 136
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsvv_contral_enable[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_contral_enable = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsvv_contral_enable[0]
};

static GUI_CONST_STORAGE unsigned char acvv_contral_enable[] = {
  _XXXXXXX, XXXXXX__, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ____XXXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, _______X, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, XXXXXXX_,
  _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXX_,
  _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, __XXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X___XXXX, X__XX___, ___XXXXX, X___XXXX, X__XXXXX, X___XXX_,
  _XXXXX__, _____XXX, XXX__XXX, XXX__XXX, XXX_XX__, __X_____, _XXXXXXX, XXXXXXXX, XXXX____, ____XXXX, X__XXXXX, X__XXXXX, X__XXXXX, X______X, XXXXXXXX, XXXXXXXX, X__XX___, _X_XX___, __XX____, XX_XX___, _X_XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XX_, __XX_XX_, ____XXX_, __X_____, _XXXXXXX, XXXXXXXX, XXXX____, ___XX___, _X___XX_, __XX____, XX_XX___, XX_____X, XXXXXXXX, XXXXXXXX, X__XX___, _X_XX___, __XX____, XX_XX___, _X_XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XX_, __XX_XX_, ____XXX_, __X_____, _XXXXXXX, XXXXXXXX, XXXX____, ___XX___, _X___XX_, __XX____, XX_XX___, XX_____X, XXXXXXXX, XXXXXXXX, X__XX___, ___XX___, __XX____, XX_XX___, ___XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XX_, __XX_XX_, ____X_XX, __X_____, _XXXXXXX, XXXXXXXX, XXXX____, ___XX___, _____XX_, __XX____, XX_XX___, XX_____X, XXXXXXXX, XXXXXXXX, X__XX___, ___XX___, __XX____, XX__XXXX, X__XXXXX, X___XXX_,
  _XXXXX__, ____XX__, __XX_XX_, __XX_XXX, XXX_X__X, X_X_____, _XXXXXXX, XXXXXXXX, XXXX____, ____XXXX, X____XX_, __XX____, XX_XX___, XX_____X, XXXXXXXX, XXXXXXXX, X__XX___, ___XX___, __XX____, XX______, XX_XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XXX, XXX__XX_, ____X__X, X_X_____, _XXXXXXX, XXXXXXXX, XXXX____, ________, XX___XX_, __XX____, XX_XXXXX, X______X, XXXXXXXX, XXXXXXXX, X__XX___, _X_XX___, __XX____, XX_X____, XX_XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XX_, _____XX_, ____X___, XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ___X____, XX___XX_, __XX____, XX_XX___, _______X, XXXXXXXX, XXXXXXXX, X__XX___, _X_XX___, __XX____, XX_X____, XX_XX___, ____XXX_,
  _XXXXX__, ____XX__, __XX_XX_, _____XX_, ____X___, XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ___X____, XX___XX_, __XX____, XX_XX___, _______X, XXXXXXXX, XXXXXXXX, X___XXXX, X__XXXXX, X__XXXXX, X___XXXX, X__XXXXX, X___XXX_,
  _XXXXX__, _____XXX, XXX__XX_, _____XXX, XXX_X___, _XX_____, _XXXXXXX, XXXXXXXX, XXXX____, ____XXXX, X____XX_, ___XXXXX, X__XX___, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ____XXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ___XXXX_,
  _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ________, __XXXXX_,
  _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _XXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, _______X, XXXXXXX_,
  _XXXXXXX, XXXXXX__, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ____XXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXX__, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ____XXXX, X__XXXXX, X___XXXX, XX___XXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ___XX___, _X_XX___, XX_XX___, _XX_XX__, __X_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ___XX___, _X_XX___, XX_XX___, _XX_XX__, __X_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ___XX___, ___XX___, XX_XX___, _XX_XX__, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ____XXXX, X__XX___, XX_XX___, _XX__XXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, XX_XXXXX, X__XX___, _XX_____, _XX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ___X____, XX_XX___, ___XX___, _XX_X___, _XX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ___X____, XX_XX___, ___XX___, _XX_X___, _XX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ____XXXX, X__XX___, ____XXXX, XX___XXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXX__, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXX_, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, X_______, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXX__, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXX_,
  _XXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ____XXXX, XX___XXX, XX___XXX, XXX__XX_, __XX_XXX, XXX_____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, __X_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, XXXXX___, XXXXXX__, XX____X_, XXXXX_XX, XX__XXXX, X_______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, __X_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X____X_X, X____XX_, XXX___X_, XX_____X, X__XX___, _X______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, ____XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X____X_X, X____XX_, XXX___X_, XX_____X, X__XX___, _X______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, XXX_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X______X, X____XX_, X_XX__X_, XX_____X, X__XX___, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, _XX_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X______X, X____XX_, X__XX_X_, XXXXX__X, X__XX__X, XX______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, _XX_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X______X, X____XX_, X__XX_X_, XX_____X, X__XX___, XX______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XX__, ___XX___, _XX_XX__, _XX_XX__, __XX_XX_, __XX___X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X____X_X, X____XX_, X___XXX_, XX_____X, X__XX___, XX______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ____XXXX, XX__XXXX, XX___XXX, XXX__XXX, XXX___XX, XXX____X, X_______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, _______X, X____X_X, X____XX_, X___XXX_, XX_____X, X__XX___, XX______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, XXXXX___, XXXXXX__, X____XX_, XX____XX, XX__XXXX, XX______, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XX______, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXX_,
  _XXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXX_,
  _XXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ___XXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_contral_enable = {
  176, /* XSize */
  136, /* YSize */
  22, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_contral_enable,  /* Pointer to picture data (indices) */
  &Palvv_contral_enable  /* Pointer to palette */
};

/* *** End of file *** */
