/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_view_open
* Dimensions:  145 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsvv_view_open[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_view_open = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsvv_view_open[0]
};

static GUI_CONST_STORAGE unsigned char acvv_view_open[] = {
  _XXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXXXXXX, ________,
  _XXXXXXX, X_______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, ________,
  _XXXXXXX, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, ________,
  _XXXXXX_, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, ________,
  _XXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXXX, _XXXXXXX, X_______, ___XXXXX, XXXXXX_X, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, X_______, ____XXXX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, X_______, ____XXXX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, X___XXXX, XX___XXX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, __XXXXXX, __XXXXXX, __XXXXXX, _XX____X, _______X, XXXXXX_X, XXXXXXXX, X___XXXX, XX___XXX, XXXXXXXX, _XXXXXXX, _XXX____, _XX__XXX, XXX_____, _XXX____, _XX_____, _X_XXXXX, ________,
  _XXX____, _XX____X, X_XX___X, X_XX____, _XXX___X, _______X, XXXXXX_X, XXXXXXXX, X___XXXX, XX___XXX, XXXXXXXX, _XXXXXXX, _XX__XXX, X_X__XXX, XX__XXXX, __X__XXX, X_X__XXX, XX_XXXXX, ________,
  _XXX____, _XX____X, X_XX___X, X_XX____, _XXX___X, _______X, XXXXXX_X, XXXXXXXX, X_______, ____XXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, X_X__XXX, XX__XXXX, __X__XXX, X_X__XXX, XX_XXXXX, ________,
  _XXX____, _XX____X, X_XX___X, X_XX____, _X_XX__X, _______X, XXXXXX_X, XXXXXXXX, X_______, ___XXXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, XXX__XXX, XX__XXXX, __X__XXX, XXX__XXX, XX_XXXXX, ________,
  _XXX____, _XX____X, X_XX___X, X_XXXXXX, _X__XX_X, _______X, XXXXXX_X, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, XXX__XXX, XX__XXXX, __XX____, _XX_____, _X_XXXXX, ________,
  _XXX____, _XX____X, X_XXXXXX, __XX____, _X__XX_X, _______X, XXXXXX_X, XXXXXXXX, X___XXX_, __XXXXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, XXX__XXX, XX__XXXX, __XXXXXX, __X__XXX, XX_XXXXX, ________,
  _XXX____, _XX____X, X_XX____, __XX____, _X___XXX, _______X, XXXXXX_X, XXXXXXXX, X___XXXX, ___XXXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, X_X__XXX, XX__XXXX, __X_XXXX, __X__XXX, XX_XXXXX, ________,
  _XXX____, _XX____X, X_XX____, __XX____, _X___XXX, _______X, XXXXXX_X, XXXXXXXX, X___XXXX, ____XXXX, XXXXXXXX, _XXXXXXX, _XX__XXX, X_X__XXX, XX__XXXX, __X_XXXX, __X__XXX, XX_XXXXX, ________,
  _XXX____, __XXXXXX, __XX____, __XXXXXX, _X____XX, _______X, XXXXXX_X, XXXXXXXX, X___XXXX, X___XXXX, XXXXXXXX, _XXXXXXX, _XXX____, _XX_____, _XX_____, _XXX____, _XX_____, _X_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, X___XXXX, XX___XXX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, X___XXXX, XX____XX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXX____, ________, ________, ________, ________, _______X, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXXX___, ________, ________, ________, ________, ______XX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, ________,
  _XXXXX__, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, ________,
  _XXXXXX_, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, ________,
  _XXXXXXX, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, ________,
  _XXXXXXX, X_______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, ________,
  _XXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ___XXXXX, XXXXXXXX, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_view_open = {
  145, /* XSize */
  32, /* YSize */
  19, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_view_open,  /* Pointer to picture data (indices) */
  &Palvv_view_open  /* Pointer to palette */
};

/* *** End of file *** */
