/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: gs_right_pressed
* Dimensions:  52 * 25
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsgs_right_pressed[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palgs_right_pressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsgs_right_pressed[0]
};

static GUI_CONST_STORAGE unsigned char acgs_right_pressed[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, __XX____,
  X_______, __XXXXXX, ________, ________, ________, ________, ___X____,
  X_______, ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, ________, ________, ________, ___X____,
  X_______, ________, ________, ________, ________, ________, __XX____,
  X_______, ________, ________, ________, ________, ________, XXXX____,
  X_______, ________, ________, ________, _______X, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _______X, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _______X, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, ______XX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  X_______, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____,
  X_______, __XXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmgs_right_pressed = {
  52, /* XSize */
  25, /* YSize */
  7, /* BytesPerLine */
  1, /* BitsPerPixel */
  acgs_right_pressed,  /* Pointer to picture data (indices) */
  &Palgs_right_pressed  /* Pointer to palette */
};

/* *** End of file *** */
