SOURCE := \
	WMTouch.c \
	WM__UpdateChildPositions.c \
	WM_UserData.c \
	WM_IsCompletelyVisible.c \
	WM__GetFocussedChild.c \
	WM__IsChild.c \
	WM_StayOnTop.c \
	WM_GetDiagInfo.c \
	WM_GetScrollbar.c \
	WM_ValidateWindow.c \
	WM_Broadcast.c \
	WM_GetOrg.c \
	WM_GetClientWindow.c \
	WM_AttachWindow.c \
	WM_GetScrollState.c \
	WM_GetScrollPartner.c \
	WM_SetCallback.c \
	WM_CriticalHandle.c \
	WM__SendMessage.c \
	WM_SetYSize.c \
	WM_Timer.c \
	WM_GetBkColor.c \
	WM__ForEachDesc.c \
	WM_OnKey.c \
	WM_Paint.c \
	WM_SetXSize.c \
	WM_IsEnabled.c \
	WM_GetWindowSize.c \
	WM__NotifyVisChanged.c \
	WM_GetDesktopWindowEx.c \
	WM_IsVisible.c \
	WM_BringToBottom.c \
	WM_Show.c \
	WM_SetFocusOnPrevChild.c \
	WM_GetDesktopWindow.c \
	WM_GetFocussedWindow.c \
	WM_GetInvalidRect.c \
	WM_SetSize.c \
	WM_SetUserClipRect.c \
	WM_DIAG.c \
	WM__IsEnabled.c \
	WMMemDev.c \
	WM_GetWindowRect.c \
	WM_SetId.c \
	WM_SetTransState.c \
	WM_SetScrollState.c \
	WM_SetDesktopColor.c \
	WM_SetCapture.c \
	WM_SetFocus.c \
	WM__Screen2Client.c \
	WM_SendToParent.c \
	WM_GetFirstChild.c \
	WM_GetInsideRect.c \
	WM_GetDialogItem.c \
	WM__SendMessageIfEnabled.c \
	WM_PID__GetPrevState.c \
	WM__GetLastSibling.c \
	WM_GetClientRect.c \
	WM_GetFlags.c \
	WM_Screen2Win.c \
	WM__GetPrevSibling.c \
	WM_NotifyParent.c \
	WM_CheckScrollPos.c \
	WM_TimerExternal.c \
	WM_GetId.c \
	WM__GetOrg_AA.c \
	WM_GetParent.c \
	WM__GetFirstSibling.c \
	WM_MakeModal.c \
	WM_SetFocusOnNextChild.c \
	WM_SetCreateFlags.c \
	WM_SetCaptureMove.c \
	WM_MoveChildTo.c \
	WM_HasFocus.c \
	WM__IsAncestor.c \
	WM_SetTrans.c \
	WM_Hide.c \
	WM_SetpfPollPID.c \
	WM_SetScrollbar.c \
	WM_HasCaptured.c \
	WM_BringToTop.c \
	WM_GetNextSibling.c \
	WM_SetAnchor.c \
	WM_ForEachDesc.c \
	WM.c \
	WM_SendMessageNoPara.c \
	WM_Move.c \
	WM_IsFocussable.c \
	WM_EnableWindow.c \
	WM_GetInsideRectExScrollbar.c \
	WM_GetPrevSibling.c \
	WM_IsWindow.c \
	WM_Validate.c \
	WM_ResizeWindow.c \
	WM__SendMessageNoPara.c

