/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_close_unpressed
* Dimensions:  43 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_close_unpressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPalette[0]
};

static GUI_CONST_STORAGE unsigned char acvv_close_unpressed[] = {
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____,
  XXXXX___, ________, ________, ________, ______XX, XXX_____,
  XXXX____, ________, ________, ________, _______X, XXX_____,
  XXX_____, ________, ________, ________, ________, XXX_____,
  XX______, ________, ________, ________, ________, _XX_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ___XXXXX, __XX____, __XXXXXX, ___XXXXX, __XXXXXX, ________,
  __XX____, __XX____, _XX____X, X_XX____, __XX____, ________,
  __XX____, X_XX____, _XX____X, X_XX____, X_XX____, ________,
  __XX____, __XX____, _XX____X, X_XX____, __XX____, ________,
  __XX____, __XX____, _XX____X, X__XXXXX, __XXXXXX, ________,
  __XX____, __XX____, _XX____X, X______X, X_XX____, ________,
  __XX____, X_XX____, _XX____X, X_X____X, X_XX____, ________,
  __XX____, __XX____, _XX____X, X_X____X, X_XX____, ________,
  ___XXXXX, __XXXXXX, __XXXXXX, ___XXXXX, __XXXXXX, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  XX______, ________, ________, ________, ________, _XX_____,
  XXX_____, ________, ________, ________, ________, XXX_____,
  XXXX____, ________, ________, ________, _______X, XXX_____,
  XXXXX___, ________, ________, ________, ______XX, XXX_____,
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_close_unpressed = {
  43, /* XSize */
  32, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_close_unpressed,  /* Pointer to picture data (indices) */
  &Palvv_close_unpressed  /* Pointer to palette */
};

/* *** End of file *** */
