/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_prev_pressed
* Dimensions:  53 * 41
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsvv_prev_pressed[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_prev_pressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsvv_prev_pressed[0]
};

static GUI_CONST_STORAGE unsigned char acvv_prev_pressed[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___,
  X_______, ________, ________, ________, ____XXXX, XX______, ___XX___,
  ________, ________, ________, ________, ____XXXX, XXX_____, ___XX___,
  ________, ________, ________, ________, ________, ________, ___XX___,
  X_______, ________, ________, ________, ________, ________, ___XX___,
  X_______, ________, ________, ________, ________, ________, ___XX___,
  XX______, ________, ________, ________, ________, ________, ___XX___,
  XXXX____, ________, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________, ___XX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XX______, ___XX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_prev_pressed = {
  53, /* XSize */
  41, /* YSize */
  7, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_prev_pressed,  /* Pointer to picture data (indices) */
  &Palvv_prev_pressed  /* Pointer to palette */
};

/* *** End of file *** */
