/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_next_pressed
* Dimensions:  53 * 41
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsvv_next_pressed[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_next_pressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsvv_next_pressed[0]
};

static GUI_CONST_STORAGE unsigned char acvv_next_pressed[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXX_____, _______X, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ___XX___,
  XX______, ___XXXXX, X_______, ________, ________, ________, ____X___,
  XX______, __XXXXXX, X_______, ________, ________, ________, ________,
  XX______, ________, ________, ________, ________, ________, ________,
  XX______, ________, ________, ________, ________, ________, ____X___,
  XX______, ________, ________, ________, ________, ________, ____X___,
  XX______, ________, ________, ________, ________, ________, ___XX___,
  XX______, ________, ________, ________, ________, ________, _XXXX___,
  XX______, ________, ________, ________, ________, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ________, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ________, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ________, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ________, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _______X, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _____XXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXX___,
  XX______, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXX___,
  XX______, ___XXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_next_pressed = {
  53, /* XSize */
  41, /* YSize */
  7, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_next_pressed,  /* Pointer to picture data (indices) */
  &Palvv_next_pressed  /* Pointer to palette */
};

/* *** End of file *** */
