/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_open_pressed
* Dimensions:  43 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_open_pressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPalette[0]
};

static GUI_CONST_STORAGE unsigned char acvv_open_pressed[] = {
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____,
  XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXX_____,
  XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXX_____,
  XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_____,
  XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXX_, _____XX_, _____XX_, _____X__, XXXX_XXX, XX______,
  _XXXXX__, XXXX__X_, _XXX__X_, _XXXXX__, _XXX_XXX, XX______,
  _XXXXX__, XXXX__X_, _XXX__X_, _XXXXX__, _XXX_XXX, XX______,
  _XXXXX__, XXXX__X_, _XXX__X_, _XXXXX_X, __XX_XXX, XX______,
  _XXXXX__, XXXX__X_, _XXX__X_, _____X_X, X__X_XXX, XX______,
  _XXXXX__, XXXX__X_, _____XX_, _XXXXX_X, X__X_XXX, XX______,
  _XXXXX__, XXXX__X_, _XXXXXX_, _XXXXX_X, XX___XXX, XX______,
  _XXXXX__, XXXX__X_, _XXXXXX_, _XXXXX_X, XX___XXX, XX______,
  _XXXXXX_, _____XX_, _XXXXXX_, _____X_X, XXX__XXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_____,
  XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_____,
  XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXX_____,
  XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXX_____,
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_open_pressed = {
  43, /* XSize */
  32, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_open_pressed,  /* Pointer to picture data (indices) */
  &Palvv_open_pressed  /* Pointer to palette */
};

/* *** End of file *** */
