/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_stop_pressed
* Dimensions:  43 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif



static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_stop_pressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPalette[0]
};

static GUI_CONST_STORAGE unsigned char acvv_stop_pressed[] = {
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____,
  XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXX_____,
  XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXX_____,
  XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_____,
  XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, X_____XX, ______XX, ______XX, ______XX, XX______,
  _XXXXXXX, __XXXX_X, XX__XXX_, _XXXX__X, __XXX__X, XX______,
  _XXXXXXX, __XXXX_X, XX__XXX_, _XXXX__X, __XXX__X, XX______,
  _XXXXXXX, __XXXXXX, XX__XXX_, _XXXX__X, __XXX__X, XX______,
  _XXXXXXX, X_____XX, XX__XXX_, _XXXX__X, __XXX__X, XX______,
  _XXXXXXX, XXXXX__X, XX__XXX_, _XXXX__X, ______XX, XX______,
  _XXXXXXX, _XXXX__X, XX__XXX_, _XXXX__X, __XXXXXX, XX______,
  _XXXXXXX, _XXXX__X, XX__XXX_, _XXXX__X, __XXXXXX, XX______,
  _XXXXXXX, X_____XX, XX__XXXX, ______XX, __XXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_____,
  XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_____,
  XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_____,
  XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXX_____,
  XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXX_____,
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_stop_pressed = {
  43, /* XSize */
  32, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_stop_pressed,  /* Pointer to picture data (indices) */
  &Palvv_stop_pressed  /* Pointer to palette */
};

/* *** End of file *** */
