/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: vv_spos_unpressed
* Dimensions:  43 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE GUI_LOGPALETTE Palvv_spos_unpressed = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &ColorsPalette[0]
};

static GUI_CONST_STORAGE unsigned char acvv_spos_unpressed[] = {
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____,
  XXXXX___, ________, ________, ________, ______XX, XXX_____,
  XXXX____, ________, ________, ________, _______X, XXX_____,
  XXX_____, ________, ________, ________, ________, XXX_____,
  XX______, ________, ________, ________, ________, _XX_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ______XX, XXX__XXX, XXX___XX, XXXX___X, XXXX____, ________,
  _____XX_, ___X_XX_, __XX_XX_, ___XX_XX, ____X___, ________,
  _____XX_, ___X_XX_, __XX_XX_, ___XX_XX, ____X___, ________,
  _____XX_, _____XX_, __XX_XX_, ___XX_XX, ________, ________,
  ______XX, XXX__XX_, __XX_XX_, ___XX__X, XXXX____, ________,
  ________, __XX_XXX, XXX__XX_, ___XX___, ___XX___, ________,
  _____X__, __XX_XX_, _____XX_, ___XX_X_, ___XX___, ________,
  _____X__, __XX_XX_, _____XX_, ___XX_X_, ___XX___, ________,
  ______XX, XXX__XX_, ______XX, XXXX___X, XXXX____, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  X_______, ________, ________, ________, ________, __X_____,
  XX______, ________, ________, ________, ________, _XX_____,
  XXX_____, ________, ________, ________, ________, XXX_____,
  XXXX____, ________, ________, ________, _______X, XXX_____,
  XXXXX___, ________, ________, ________, ______XX, XXX_____,
  XXXXXXXX, ________, ________, ________, ___XXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmvv_spos_unpressed = {
  43, /* XSize */
  32, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acvv_spos_unpressed,  /* Pointer to picture data (indices) */
  &Palvv_spos_unpressed  /* Pointer to palette */
};

/* *** End of file *** */
